# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "CREATE UNSW: Build - Learn - Inspire"
email: create@createunsw.com.au
sales_email: sales@createunsw.com.au
description: A student-led maker club based at UNSW Sydney. CREATE UNSW runs and provides workshops for beginners on electronics, programming, soldering, prototyping and 3D modelling. Weekly sales of electronic components on-campus, including Kits. Hackerspaces and makerspaces. Quadcopters. Funding and support for student projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site, e.g. http://example.com
github_username: createunsw
facebook: https://www.facebook.com/CreateUnsw/
instagram: https://www.instagram.com/createunsw/
linkedin: https://www.linkedin.com/company/create-nsw-inc-/
youtube: https://www.youtube.com/user/createunsw/


#club logo
logo-pos: /images/logos/create_logo_2019T3-POS.png
logo-neg: /images/logos/create_logo_2019T3-NEG.png

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

sass:
  sass_dir: "/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  _catalogues:
    output: true
  _media:
    output: true
    permalink: /media/:categories/:title/
  _products:
    output: true
    permalink: /store/:title/
  _projects:
    output: true
    permalink: /projects/:title/
  _invoices:
    output: true
    permalink: /invoices/:title/
  _people:
    output: false
  _pages:
    output: true
    permalink: /:name/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "__catalogues"
    values:
      layout: "catalogue"
  -
    scope:
      path: "__media"
    values:
      layout: "post"
  -
    scope:
      path: "__products"
    values:
      layout: "productdetails"
  -
    scope:
      path: "__projects"
    values:
      layout: "projectsite"
  - scope:
      path: "__invoices"
    values:
      layout: "invoice"
